### ISSUE TITLE
使用github action实现自动化测试，自动化发布

### ISSUE THREAD

**Issue by thomas-void0** [thomas-void0/blogs#104]
# 自动测试
在推送代码到main分支的时候，自动测试推送的代码
```yml
name: Test

on:
  push:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        version: [14.x, 16.x, 18.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: 'npm'
      - run: npm ci --force
      - run: npm run test
```
# 自动发布npm包
在手动release一个版本的时候，自动发布到npm
```yml
name: Publish
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci --force
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```
需要注意的是`secrets.NPM_TOKEN`需要创建一个[npm token](https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow)用户发布。创建好npm token后，在对应github仓库的settings中配置
![image](https://user-images.githubusercontent.com/48620706/221737093-834ae58f-11e1-4022-911b-4a2ab171a154.png)
