### ISSUE TITLE
使用github action构建镜像推送到阿里云

### ISSUE THREAD

**Issue by thomas-void0** [thomas-void0/blogs#105]
# 自动化脚本命令
```yml
# 工作流程的名称
name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Ali Docker
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
          username: ${{ secrets.ALI_DOCKER_HUB_USN }}
          password: ${{ secrets.ALI_DOCKER_HUB_PWD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.cn-chengdu.aliyuncs.com/thomas-void0/react-template
```
# 在仓库中设置对应的信息
![image](https://user-images.githubusercontent.com/48620706/221775832-8ee34b02-461e-41cc-8634-17b2645fcb3c.png)
