### ISSUE TITLE
css画三角形

### ISSUE THREAD

**Issue by thomas-void0** [thomas-void0/blogs#65]
```css

.arrow{
    height: 0px;
    width: 0px;
    border-top:50px solid pink;
    border-right:50px solid black;
    border-bottom:50px solid red;
    border-left:50px solid beige;
}
```
