### ISSUE TITLE
css骨架屏动画效果

### ISSUE THREAD

**Issue by thomas-void0** [thomas-void0/blogs#76]
![image](https://user-images.githubusercontent.com/48620706/203702984-9f120a55-801a-46c4-b35f-6187716e5a76.png)

```css
@keyframes skeleton-loading {
  0% {
	  background-position: 100% 50%;
  }
  100% {
	  background-position: 0 50%;
  }
}

.skeleton {
  background-image: linear-gradient(
	  90deg,
	  rgba(190, 190, 190, 0.2) 25%,
	  rgba(129, 129, 129, 0.24) 37%,
	  rgba(190, 190, 190, 0.2) 63%
  );
  width: 100%;
  height: 40px;
  background-size: 400% 100%;
  background-position: 100% 50%;
  animation: skeleton-loading 1.4s ease infinite;
}
```
